
package org.soap.controller;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatalogInterface", targetNamespace = "http://controller.soap.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatalogInterface {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductCategories", targetNamespace = "http://controller.soap.org/", className = "org.soap.controller.GetProductCategories")
    @ResponseWrapper(localName = "getProductCategoriesResponse", targetNamespace = "http://controller.soap.org/", className = "org.soap.controller.GetProductCategoriesResponse")
    @Action(input = "http://controller.soap.org/ProductCatalogInterface/getProductCategoriesRequest", output = "http://controller.soap.org/ProductCatalogInterface/getProductCategoriesResponse")
    public List<String> getProductCategories();

    /**
     * 
     * @param lookupInput
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "lookupOutput", targetNamespace = "")
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://controller.soap.org/", className = "org.soap.controller.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://controller.soap.org/", className = "org.soap.controller.GetProductResponse")
    @Action(input = "http://controller.soap.org/ProductCatalogInterface/getProductRequest", output = "http://controller.soap.org/ProductCatalogInterface/getProductResponse")
    public List<String> getProduct(
        @WebParam(name = "lookupInput", targetNamespace = "")
        String lookupInput);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://controller.soap.org/", className = "org.soap.controller.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://controller.soap.org/", className = "org.soap.controller.AddProductResponse")
    @Action(input = "http://controller.soap.org/ProductCatalogInterface/addProductRequest", output = "http://controller.soap.org/ProductCatalogInterface/addProductResponse")
    public boolean addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(action = "delete_soap")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteIT", targetNamespace = "http://controller.soap.org/", className = "org.soap.controller.DeleteIT")
    @ResponseWrapper(localName = "deleteITResponse", targetNamespace = "http://controller.soap.org/", className = "org.soap.controller.DeleteITResponse")
    @Action(input = "delete_soap", output = "http://controller.soap.org/ProductCatalogInterface/deleteITResponse")
    public boolean deleteIT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param productInput
     * @return
     *     returns java.util.List<org.soap.controller.ProductDetails>
     */
    @WebMethod
    @WebResult(name = "ProductDetails", targetNamespace = "")
    @RequestWrapper(localName = "getProductV2", targetNamespace = "http://controller.soap.org/", className = "org.soap.controller.GetProductV2")
    @ResponseWrapper(localName = "getProductV2Response", targetNamespace = "http://controller.soap.org/", className = "org.soap.controller.GetProductV2Response")
    @Action(input = "http://controller.soap.org/ProductCatalogInterface/getProductV2Request", output = "http://controller.soap.org/ProductCatalogInterface/getProductV2Response")
    public List<ProductDetails> getProductV2(
        @WebParam(name = "productInput", targetNamespace = "")
        String productInput);

}
